main: fr.dariusmtn.minetrain.Main
version: 1.0
name: MineTrain
author: Slaymd
commands:
  minetrain:
    description: MineTrain main command.
    aliases: [mt,mtn]
  minetrainconfig:
    description: MineTrain config command.
    aliases: [mtc,mtnc]